#!/usr/bin/env bash

layout=$(setxkbmap -query | grep layout | awk '{print $2}')

case $layout in
  "us")
    next_layout=cz
    ;;
  "cz")
    next_layout=us
    ;;
  *)
    next_layout=us
    ;;
esac

setxkbmap -layout $next_layout
notify-send --expire-time=1500 "Keyboard layout: $next_layout" -h string:x-canonical-private-synchronous:keyboard_layout

