#!/usr/bin/env bash

volume_level=`pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`


if [[ $volume_level -gt 100 ]]; then
	echo "<fc=#ff0000>+$((volume_level-100))</fc>"
fi
exit 0

mute=`pactl list sinks | grep '^[[:space:]]Mute:' | awk '{ print $2}'`

case $mute in
"no")
	if [[ $volume_level -gt 100 ]]; then
		echo '<fc=#ff0000>|||||</fc>'
	elif [[ $volume_level -gt 80 ]]; then
		echo '|||||'
	elif [[ $volume_level -gt 60 ]]; then
		echo '||||:'
	elif [[ $volume_level -gt 40 ]]; then
		echo '|||::'
	elif [[ $volume_level -gt 20 ]]; then
		echo '||:::'
	elif [[ $volume_level -gt 0 ]]; then
		echo '|::::'
	else
		echo ':::::'
	fi
	;;
*)
	echo '-----'
	;;
esac

