#!/usr/bin/env bash

USER=valoudav
HOST=login.rci.cvut.cz

MOUNTPOINT=/mnt/rcihome

if [[ $1 = '-u' ]]
then
	echo "Unmounting to $MOUNTPOINT ..."
	fusermount -u $MOUNTPOINT \
		&& echo OK
else
	echo "Mounting $MOUNTPOINT ..."
	sshfs $USER@$HOST:/home/$USER $MOUNTPOINT \
		&& echo OK
fi
